### PR TITLE
Expose a search query parameter

### LINKED ISSUE #144: Expose a search query parameter
It would be nice to be able to link to a search.

For example, in IRC the topic of elm-history came up and how the 0.16 version was hosted at a new location.

Being able to link to e.g. `/?q=history` would've been a nice way to communicate together the status of elm-history and also the new location it can be found at:

screenshot

Additional polish would entail auto-updating the `?q=...` query parameter (without changing the history stack) and also removing the parameter from the url when the user clicks out of search.

### PR DESCRIPTION
**Pull request by jb55**
Fixes #144 

/cc @danneu

### CODE REVIEW

**Comment by jb55** [comment]
Anything else that needs to be done here? No rush.

**Comment by evancz** [comment]
The plan is to come do a big chunk of work on elm-package and the website after 0.18 and everything that's going into that. So this will get visited then. If you look for status reports on elm-dev, you can find more info about this kind of thing!

**Comment by jb55** [comment]
Sounds good :+1:

**Comment by evancz** [comment]
We may do this with `replaceUrl` in the future, but I want to hold off on it for now.

**Pull request closed without merging**
