### PR TITLE
Make the website responsive

### PR DESCRIPTION
**Pull request by Warry**
Allows to conveniently browse the website with a small window: no horizontal scrollbar, displays the menu at the top.

### CODE REVIEW

**Comment by evancz** [comment]
Can you show images of what it'd look like on all the different pages with this change?

**Comment by Warry** [comment]
Here they are:

home
home-scrolled
package-home
package-scrolled

There is a remaining horizontal scrollbar when some content is too large.

**Comment by Warry** [comment]
To try it live, you can also add the following to the css (in browser's debugger > sources > assets > styles.css):

```/* RESPONSIVENESS */
@media (max-width: 960px) {
  .center {
    width: auto;
    margin-left: 10px;
    margin-right: 10px;
    flex-direction: column;
    display: flex;
  }

  .block-list, .catalog {
    width: auto;
    display: block;
  }
 
  .pkg-nav, .catalog-sidebar {
    width: auto;
    display: block;
    padding: 0px;
    margin: 20px;
    border-left: none;
    order: -1;
  }

  .catalog input {
    width: 90%;
    margin: 10px auto;
  }
}```

**Comment by evancz** [comment]
I think the first step to any project like this is to do mocks. I think the thing suggested here is convenient with CSS, but I'm not sure it's coming from "what would be nice in that format?" and I'm not 100% if browsing docs on phones is a common scenario.

Point is, I think the first step is to figure out:

1. Who is searching docs on their phone?
2. What are they looking for in that particular scenario?

I think that is a prerequisite for the design.

**Comment by wking-io** [comment]
I will try and get theses answers and get more research done and come back to this issue!

**Comment by Warry** [comment]
Hi @evancz, I'm not using the site on a phone,but I'm coding with a splitted screen most of the time:
screenshot from 2018-08-30 22-42-58

**Comment by evancz** [comment]
@wking-io, just make a new issue. Long issues are really hard to deal with. They always become about multiple things!

@Warry, same logic still applies. Rather than doing something that's convenient in CSS, it makes sense to figure out what'd actually be nice for that scenario.

**Comment by bobwhitelock** [comment]
> I think the thing suggested here is convenient with CSS, but I'm not sure it's coming from "what would be nice in that format?" and I'm not 100% if browsing docs on phones is a common scenario.

Given that the current website is not very responsive at the moment, and the changes made here do seem to improve this (without a downside as far as I can see, though maybe I've missed what that is), why not merge this to improve things for now until someone can circle back and investigate what the ideal mobile/small screen experience might be? :slightly_smiling_face:

**Pull request closed without merging**
